# -*- coding: utf-8 -*-
"""p1s1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oXkZADzGod2rHM0qZJz5PsVYP6b1Rre0
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

dataset = pd.read_csv('train.csv')
X = dataset.iloc[ : , :-1].values
y = dataset.iloc[:,-1].values
dataset2 = pd.read_csv('test.csv')
X_test = dataset2.iloc[ : , :-1].values
y_test = dataset2.iloc[:,-1].values

print(X)
print(X.shape[1])

print(X_test)
print(X_test.shape[1])
print(len(X_test))

# print(y_test)
print(y_test.shape)

def correlation_matrix(df: pd.DataFrame):
    """
    A function to calculate and plot
    correlation matrix of a DataFrame.
    """
    # Create the matrix
    matrix = df.corr()
    print(matrix)
    
    # Create cmap
    cmap = sns.diverging_palette(250, 15, s=75, l=40,
                             n=20, center="light", as_cmap=True)
    # Create a mask
    mask = np.triu(np.ones_like(matrix, dtype=bool))
    
    # Make figsize bigger
    fig, ax = plt.subplots(figsize=(12,8))
    
    # Plot the matrix
    hm=sns.heatmap(data=matrix,annot=True)

correlation_matrix(dataset)